@startuml
' Définition des classes

class Utilisateur {
  id : int
  nom : string
  prenom : string
  mot_de_passe : string
  Email : string
}

class Client {
  Telephone : string
  Ajouter_client()
  Annuler_client()
  Consulter_client()
}

class Admin {
  Ajouter_chambre()
  Consulter_chambre()
  Supprimer_chambre()
}

class Chambre {
  id_chambre : int
  Type : string
  Etat_chambre : string
  Prix : float
  Ajouter_chambre()
  Consulter_chambre()
  Supprimer_chambre()
}

class Reservation {
  id_Reservation : int
  Date_debut : date
  Date_fin : date
  Montant : float
  Type_sejour : string
  nombre_adulte : int
  nombre_enfant : int
  Ajouter_reservation()
  Consulter_reservation()
  Supprimer_reservation()
  Calculer_montant()
}

' Héritage

Utilisateur <|-- Client
Utilisateur <|-- Admin

' Relations
Client "1..*" -- "1..1" Admin : Gérer
Client "1..1" -- "1..*" Reservation : Ajouter
Client "1..1" -- "1..*" Reservation : consulter
Client "1..1" -- "1..*" Reservation : Supprimer
Admin "1..1" -- "1..*" Chambre: Gérer
Admin "1..1" -- "1..*"Reservation: Gérer
Chambre "1..*" -- "1..1" Reservation : Contenir


@enduml
